#!/usr/bin/env bash

# If you don't care about using fixed versions of moar, nqp, and raku, just use
# the automatic installation script:
#
# curl https://rakubrew.org/install-on-perl.sh | sh

export DEBIAN_FRONTEND="noninteractive"

apt-get install -y --no-install-recommends \
	build-essential \
	ca-certificates \
	git \
	libuv1-dev \
	libzstd-dev \
	wget

# The makefile generated by Configure.pl points to /home/runner/work/MoarVM...
# Not sure how to change/fix it, except to manually search/replace.
function patch_makefile {
	local search='/home/runner/work/MoarVM/MoarVM/MoarVM.ubuntu-24.04'
	local replace='/opt/raku/2026.03'

	find . -type f -exec sed -i "s|$search|$replace|g" {} +
}

mkdir '/opt/raku'

mkdir '/tmp/moar'
pushd '/tmp/moar'
wget -q 'https://github.com/MoarVM/MoarVM/releases/download/2026.03/MoarVM.ubuntu-24.04.tar.gz'
printf '%s  %s\n' '12e0ac9e11b7b2e70bb562127e441b6c7acae1c4' 'MoarVM.ubuntu-24.04.tar.gz' | sha1sum --check -
tar -xf 'MoarVM.ubuntu-24.04.tar.gz' -C '/opt/raku'
mv '/opt/raku/MoarVM.ubuntu-24.04' '/opt/raku/2026.03'
popd
rm -fr '/tmp/moar'
ln -s '/opt/raku/2026.03/bin/moar' '/usr/bin/moar'

mkdir '/tmp/nqp'
pushd '/tmp/nqp'
wget -q 'https://github.com/Raku/nqp/releases/download/2026.03/nqp-2026.03.tar.gz'
printf '%s  %s\n' '3272ba447ee968a3108493263fc0a93bf8c306ee' 'nqp-2026.03.tar.gz' | sha1sum --check -
tar -xf 'nqp-2026.03.tar.gz'
pushd 'nqp-2026.03'
perl 'Configure.pl' --backends='moar' --with-moar='/opt/raku/2026.03/bin/moar'
patch_makefile
make
make install
popd; popd
rm -fr '/tmp/nqp'
ln -s '/opt/raku/2026.03/bin/nqp' '/usr/bin/nqp'
ln -s '/opt/raku/2026.03/bin/nqp-m' '/usr/bin/nqp-m'

mkdir '/tmp/raku'
pushd '/tmp/raku'
wget -q 'https://github.com/rakudo/rakudo/releases/download/2026.03/rakudo-2026.03.tar.gz'
printf '%s  %s\n' '08fd8cc9ff31f91a8cc24429deeaf37166f68329' 'rakudo-2026.03.tar.gz' | sha1sum --check -
tar -xf 'rakudo-2026.03.tar.gz'
pushd 'rakudo-2026.03'
perl 'Configure.pl' --backends='moar' --prefix='/opt/raku/2026.03'
patch_makefile
make
make install
popd; popd
rm -fr '/tmp/raku'
ln -s '/opt/raku/2026.03/bin/rakudo' '/usr/bin/rakudo'
ln -s '/opt/raku/2026.03/bin/rakudo' '/usr/bin/raku'
